# -*- coding: utf-8 -*-
"""DecisionTree_Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wgx4vYxPeQx1Hp8SlWtG8pKlzzmS2Wm_

# **Decision Tree**

### **Importing library**


---
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

"""## **Importing Dataset**

---


"""

dataset= pd.read_csv('Position_Salaries.csv' )
x=dataset.iloc[:,1:-1].values
y=dataset.iloc[:,-1].values

"""## **Training the Decision Tree model on whole Dataset**

---


"""

from sklearn.tree import DecisionTreeRegressor
regressor=DecisionTreeRegressor(random_state=0)
regressor.fit(x,y)

"""## **Predicting a new Result**

---


"""

regressor.predict([[6.5]])

"""## **Visualizing the Result**

---


"""

X_grid = np.arange(min(x), max(x), 0.01)
X_grid = X_grid.reshape((len(X_grid), 1))
plt.scatter(x, y, color = 'red')
plt.plot(X_grid, regressor.predict(X_grid), color = 'blue')
plt.title('Truth or Bluff (Decision Tree Regression)')
plt.xlabel('Position level')
plt.ylabel('Salary')
plt.show()