# -*- coding: utf-8 -*-
"""Multi Linear Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/126Z3U50mUi-EOmGCRg4pT9MZ4xPCR2e5

# **Multi Linear Regression**

## **Importing Libraries**

---
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

"""## **Importing Dataset**"""

dataset= pd.read_csv('50_Startups.csv')
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

"""## **Encoding Categorical Data**"""

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[3])] , remainder='passthrough')
x=np.array(ct.fit_transform(x))

"""## **Splitting into Test and Training DataSet**"""

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

"""## **Training the model on Training DataSet**"""

from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train)

"""## **Predicting the Test Set Results**

"""

y_pred = regressor.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), axis=1))