# -*- coding: utf-8 -*-
"""polynomial_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EvjY0P_StXbq481XLq1Xx1XN_Feo6OGQ

# **Polynomial Linear Regression**

## **Importing Libraries**

---
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

"""## **Importing Dataset**

---



"""

dataset= pd.read_csv('Position_Salaries.csv')
x=dataset.iloc[:,1:-1].values
y=dataset.iloc[:,-1].values

"""## **Training the Linear Regression model on Whole Dataset**

---


"""

from sklearn.linear_model import LinearRegression
lin_reg=LinearRegression()
lin_reg.fit(x,y)

"""## **Training the Polynomial Regression model on Whole Dataset**

---


"""

from sklearn.preprocessing import PolynomialFeatures
poly_reg=PolynomialFeatures(degree=4)
x_poly=poly_reg.fit_transform(x)
lin_Reg2=LinearRegression()
lin_Reg2.fit(x_poly,y)

"""## **Visualizing the Results of the Linear Regression Model**

---


"""

plt.scatter(x,y,color='Red')
plt.plot(x,lin_reg.predict(x),color='Blue')
plt.title('Truth or Bluff')
plt.xlabel('Levels')
plt.ylabel('Salary')
plt.show()

"""## **Visualizing the Results of the Polynomial Regression Model**

---


"""

plt.scatter(x,y,color='Red')
plt.plot(x,lin_Reg2.predict(poly_reg.fit_transform(x)),color='Blue')
plt.title('Truth or Bluff')
plt.xlabel('Levels')
plt.ylabel('Salary')
plt.show()

"""## **Predicting with Linear Regression Model**

---


"""

lin_reg.predict([[6.5]])

"""## **Predicting with Polynomial Regression Model**

---


"""

lin_Reg2.predict(poly_reg.fit_transform([[6.5]]))