# -*- coding: utf-8 -*-
"""RandomForest_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1582TTCTYWKtFD--wNaneYkBnnULHmrVS

# **Random Forest Regression**

## **Importing Library**
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

"""## **Importing Dataset**"""

dataset= pd.read_csv('Position_Salaries.csv' )
x=dataset.iloc[:,1:-1].values
y=dataset.iloc[:,-1].values

"""## **Training the Random Forest on Whole DataSet**"""

from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor(n_estimators=20)
regressor.fit(x,y)

"""## **Predicting the New Result**"""

regressor.predict([[6.5]])

"""## **Visualizing the Result of Random Forest(High Resolution)**"""

X_grid = np.arange(min(x), max(x), 0.01)
X_grid = X_grid.reshape((len(X_grid), 1))
plt.scatter(x, y, color = 'red')
plt.plot(X_grid, regressor.predict(X_grid), color = 'blue')
plt.title('Truth or Bluff (Random Forest Regression)')
plt.xlabel('Position level')
plt.ylabel('Salary')
plt.show()