# -*- coding: utf-8 -*-
"""SupportVector_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-7lHIqYaxpVgSGopz1Ye_CPvq1HHvxH5

# **Support Vector Regression**

## **Importing Libraries**
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

"""## **Importing Dataset**"""

dataset= pd.read_csv('Position_Salaries.csv' )
x=dataset.iloc[:,1:-1].values
y=dataset.iloc[:,-1].values

y=y.reshape(len(y),1)

"""## **Feature Scaling**"""

from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
sc_y=StandardScaler()
x=sc_x.fit_transform(x)
y=sc_y.fit_transform(y)

"""## **Training SVR model on whole DataSet**"""

from sklearn.svm import SVR
regressor=SVR(kernel='rbf')
regressor.fit(x,y)

"""## **Predicting a new result**"""

sc_y.inverse_transform(regressor.predict(sc_x.transform([[6.5]])).reshape(-1,1))

"""## **Visualising SVR result**"""

plt.scatter(sc_x.inverse_transform(x),sc_y.inverse_transform(y),color='Red')
plt.plot(sc_x.transform(x),sc_y.inverse_transform(regressor.predict(x).reshape(-1,1)),color='Blue')
plt.title('Truth or Bluff')
plt.xlabel('Levels')
plt.ylabel('Salary')
plt.show()